"""
report.py
Generates a clean, downloadable PDF health report for a user, and a CSV export
of their raw history. Uses fpdf2 - pure Python, no native/C dependencies, so it
runs reliably on Vercel's serverless Python runtime.
"""

import io
import csv
from datetime import datetime
from fpdf import FPDF


class ReportPDF(FPDF):
    def header(self):
        self.set_font("Helvetica", "B", 18)
        self.set_text_color(23, 32, 43)
        self.cell(0, 12, "Vitals - Health Report", ln=True)
        self.set_font("Helvetica", "", 10)
        self.set_text_color(91, 100, 114)
        self.cell(0, 6, "Generated " + datetime.utcnow().strftime("%d %b %Y, %H:%M UTC"), ln=True)
        self.ln(4)
        self.set_draw_color(222, 220, 211)
        self.line(10, self.get_y(), 200, self.get_y())
        self.ln(6)

    def footer(self):
        self.set_y(-15)
        self.set_font("Helvetica", "I", 8)
        self.set_text_color(150, 150, 150)
        self.cell(0, 10, "Generated by Vitals - BMI Health Tracker", align="C")


def generate_pdf_report(username, latest, history, goal=None):
    """
    latest: the most recent record dict (from db.get_records, last item)
    history: full list of records for the trend/history table
    goal: optional dict from compute_goal_progress()
    Returns raw PDF bytes.
    """
    pdf = ReportPDF()
    pdf.add_page()

    pdf.set_font("Helvetica", "B", 14)
    pdf.set_text_color(23, 32, 43)
    pdf.cell(0, 10, "Summary for " + username, ln=True)
    pdf.ln(2)

    pdf.set_font("Helvetica", "", 11)
    rows = [
        ("BMI", str(latest["bmi"]) + " (" + latest["category"] + ")"),
        ("Weight", str(latest["weight_kg"]) + " kg"),
        ("Height", str(latest["height_m"]) + " m"),
    ]
    if latest.get("bmr"):
        rows.append(("BMR (resting)", str(round(latest["bmr"])) + " kcal/day"))
    if latest.get("daily_calories"):
        rows.append(("Estimated daily calories", str(round(latest["daily_calories"])) + " kcal/day"))
    if latest.get("ideal_weight_min"):
        rows.append(("Healthy weight range",
                      str(latest["ideal_weight_min"]) + "-" + str(latest["ideal_weight_max"]) + " kg"))

    for label, value in rows:
        pdf.set_font("Helvetica", "B", 11)
        pdf.cell(60, 8, label, border=0)
        pdf.set_font("Helvetica", "", 11)
        pdf.cell(0, 8, str(value), ln=True)

    if goal:
        pdf.ln(4)
        pdf.set_font("Helvetica", "B", 12)
        pdf.cell(0, 8, "Goal Progress", ln=True)
        pdf.set_font("Helvetica", "", 11)
        pdf.cell(0, 7,
                 str(goal["start_weight"]) + " kg -> " + str(goal["current_weight"]) +
                 " kg -> goal " + str(goal["goal_weight"]) + " kg  (" + str(goal["percent"]) + "% there)",
                 ln=True)

    pdf.ln(8)
    pdf.set_font("Helvetica", "B", 12)
    pdf.cell(0, 8, "History", ln=True)
    pdf.ln(1)

    col_widths = [35, 30, 30, 25, 35]
    headers = ["Date", "Weight (kg)", "Height (m)", "BMI", "Category"]

    pdf.set_font("Helvetica", "B", 9)
    pdf.set_fill_color(228, 240, 238)
    for w, h in zip(col_widths, headers):
        pdf.cell(w, 8, h, border=1, fill=True)
    pdf.ln()

    pdf.set_font("Helvetica", "", 9)
    for record in reversed(history):
        raw_date = record["created_at"]
        date_str = str(raw_date).split(".")[0].split(" ")[0] if raw_date else ""
        values = [date_str, str(record["weight_kg"]), str(record["height_m"]),
                  str(record["bmi"]), record["category"]]
        for w, v in zip(col_widths, values):
            pdf.cell(w, 7, v, border=1)
        pdf.ln()

    return bytes(pdf.output())


def generate_csv_export(history):
    """Returns a CSV string of a user's full history."""
    output = io.StringIO()
    writer = csv.writer(output)
    writer.writerow(["Date", "Weight (kg)", "Height (m)", "BMI", "Category",
                      "Age", "Gender", "Activity Level", "BMR", "Daily Calories"])
    for record in history:
        writer.writerow([
            record.get("created_at", ""),
            record.get("weight_kg", ""),
            record.get("height_m", ""),
            record.get("bmi", ""),
            record.get("category", ""),
            record.get("age", ""),
            record.get("gender", ""),
            record.get("activity_level", ""),
            record.get("bmr", ""),
            record.get("daily_calories", ""),
        ])
    return output.getvalue()
