"""
app/services/report_service.py
Generates a downloadable PDF health report and a CSV export of raw history.
Uses fpdf2 (pure Python, no native/C dependencies) so it runs reliably on
serverless Python runtimes such as Vercel's.
"""

import io
import csv
from datetime import datetime
from fpdf import FPDF


class ReportPDF(FPDF):
    def header(self):
        self.set_font("Helvetica", "B", 18)
        self.set_text_color(23, 32, 43)
        self.cell(0, 12, "VITALS+ Health Report", ln=True)
        self.set_font("Helvetica", "", 9)
        self.set_text_color(91, 100, 114)
        self.cell(0, 6, "Generated " + datetime.utcnow().strftime("%d %b %Y, %H:%M UTC") +
                  "  |  Wellness tracking only - not a medical diagnosis.", ln=True)
        self.ln(4)
        self.set_draw_color(222, 220, 211)
        self.line(10, self.get_y(), 200, self.get_y())
        self.ln(6)

    def footer(self):
        self.set_y(-15)
        self.set_font("Helvetica", "I", 8)
        self.set_text_color(150, 150, 150)
        self.cell(0, 10, "Generated by VITALS+ - Personal Health & Fitness Analytics Platform", align="C")

    def section_title(self, text):
        self.set_font("Helvetica", "B", 12)
        self.set_text_color(23, 32, 43)
        self.cell(0, 9, text, ln=True)
        self.ln(1)

    def kv_row(self, label, value):
        self.set_font("Helvetica", "B", 10)
        self.cell(60, 7, label, border=0)
        self.set_font("Helvetica", "", 10)
        self.cell(0, 7, str(value), ln=True)


def _draw_line_chart(pdf: FPDF, x: float, y: float, w: float, h: float, values: list, label: str):
    """A minimal, dependency-free line chart drawn with fpdf primitives."""
    if len(values) < 2:
        return
    pdf.set_draw_color(200, 200, 200)
    pdf.rect(x, y, w, h)

    lo, hi = min(values), max(values)
    span = (hi - lo) or 1
    step_x = w / (len(values) - 1)

    pdf.set_draw_color(15, 110, 99)
    prev_point = None
    for i, v in enumerate(values):
        px = x + i * step_x
        py = y + h - ((v - lo) / span) * h
        if prev_point:
            pdf.line(prev_point[0], prev_point[1], px, py)
        prev_point = (px, py)

    pdf.set_font("Helvetica", "", 7)
    pdf.set_text_color(120, 120, 120)
    pdf.set_xy(x, y + h + 1)
    pdf.cell(w, 4, f"{label}: {lo} - {hi}", align="C")


def generate_pdf_report(username: str, profile: dict, latest: dict, records: list,
                         goal_summary: dict = None, insights: list = None) -> bytes:
    pdf = ReportPDF()
    pdf.add_page()

    pdf.set_font("Helvetica", "B", 14)
    pdf.set_text_color(23, 32, 43)
    pdf.cell(0, 10, f"Summary for {username}", ln=True)
    pdf.ln(2)

    pdf.section_title("Current Metrics")
    pdf.kv_row("BMI", f"{latest['bmi']} ({latest['category']})")
    pdf.kv_row("Weight", f"{latest['weight_kg']} kg")
    pdf.kv_row("Height", f"{latest['height_m']} m")
    if profile:
        pdf.kv_row("Age", profile.get("age") or "-")
        pdf.kv_row("Activity level", (profile.get("activity_level") or "-").replace("_", " ").title())
    pdf.ln(3)

    if goal_summary and goal_summary.get("progress"):
        pdf.section_title("Goal Progress")
        p = goal_summary["progress"]
        pdf.kv_row("Goal", f"{goal_summary['goal_type'].title()} to {goal_summary['target_weight_kg']} kg")
        pdf.kv_row("Progress", f"{p['start_weight']} kg -> {p['current_weight']} kg -> "
                                f"target {p['target_weight']} kg  ({p['percent']}% there)")
        completion = goal_summary.get("estimated_completion") or {}
        if completion.get("available"):
            pdf.kv_row("Est. completion", completion.get("eta_date") or "-")
        pdf.ln(3)

    weights = [r["weight_kg"] for r in records]
    if len(weights) >= 2:
        pdf.section_title("Weight Trend")
        _draw_line_chart(pdf, pdf.get_x(), pdf.get_y(), 180, 35, weights, "Weight (kg)")
        pdf.ln(42)

    if insights:
        pdf.section_title("Wellness Insights")
        pdf.set_font("Helvetica", "", 10)
        for note in insights[:6]:
            pdf.set_x(pdf.l_margin)
            pdf.multi_cell(0, 6, f"- {note}")
        pdf.ln(3)

    pdf.section_title("History")
    col_widths = [30, 25, 20, 20, 25, 25]
    headers = ["Date", "Weight (kg)", "BMI", "Steps", "Sleep (h)", "Category"]
    pdf.set_font("Helvetica", "B", 8)
    pdf.set_fill_color(228, 240, 238)
    for w, h_ in zip(col_widths, headers):
        pdf.cell(w, 7, h_, border=1, fill=True)
    pdf.ln()

    pdf.set_font("Helvetica", "", 8)
    for record in reversed(records[-30:]):
        values = [
            str(record.get("entry_date", "")),
            str(record.get("weight_kg", "")),
            str(record.get("bmi", "")),
            str(record.get("steps") or "-"),
            str(record.get("sleep_hours") or "-"),
            str(record.get("category", "")),
        ]
        for w, v in zip(col_widths, values):
            pdf.cell(w, 6, v, border=1)
        pdf.ln()

    return bytes(pdf.output())


def generate_csv_export(records: list) -> str:
    output = io.StringIO()
    writer = csv.writer(output)
    writer.writerow(["Date", "Weight (kg)", "Height (m)", "BMI", "Category",
                      "Waist (cm)", "Water (L)", "Steps", "Sleep (h)", "Calories"])
    for r in records:
        writer.writerow([
            r.get("entry_date", ""), r.get("weight_kg", ""), r.get("height_m", ""),
            r.get("bmi", ""), r.get("category", ""), r.get("waist_cm", ""),
            r.get("water_l", ""), r.get("steps", ""), r.get("sleep_hours", ""),
            r.get("calories", ""),
        ])
    return output.getvalue()
